---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ishaphere-bot
  namespace: ishaphere
  labels:
    app: ishaphere-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ishaphere-bot
  template:
    metadata:
      labels:
        app: ishaphere-bot
    spec:
      containers:
      - name: ishaphere-bot
        image: jeanluclariviere/ishaphere-bot:v0.1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /usr/src/app/config.json
          subPath: config.json
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: ishaphere-config